### PR TITLE
Dk issue 7

### PR DESCRIPTION
**Pull request by DavidKnott**
this is issue 7, I followed the user stories as closely as possible and will finish the login features in future issues
__>>ALL TESTS PASSING

### CODE REVIEW

**Comment by ethanbennett** [comment]
@DavidKnott I just fixed a merge conflict in routes, will you take a look and make sure it's what you intended before I merge?

**Review by riverswb — APPROVED** [review]
Looks good to me. Nice work!

**Comment by riverswb** [comment]
Ah, Ethan's conflict fix is probably why I had to refresh while looking through

**Comment by DavidKnott** [comment]
It's not exactly
How do i mess with it now before we commit?

**Comment by DavidKnott** [comment]
Actually I can fix it on the next merge it's not a big issue

**Comment by DavidKnott** [comment]
Ready for someone to merge

**Comment by ethanbennett** [comment]
You could just fix it in your routes file locally and push it up, the conflict shouldn't happen again now.

**Comment by riverswb** [comment]
If it is minor, you can change through the online editor by clicking "view changes" right above Ethan's comment then clicking the pencil

**Pull request merged**
