### PR TITLE
Br issue six

### PR DESCRIPTION
**Pull request by riverswb**
@Sh1pley @DavidKnott @ethanbennett 

This adds functionality to change the quantity of an item through the cart#show view with a + & - button.

All tests are passing.

### CODE REVIEW

**Comment by DavidKnott** [comment]
It has a conflict, probably because i just Merged jesses branch

**Comment by DavidKnott** [comment]
I fixed it, it was just a simple extra line.  Now it looks good and ready to merge

**Comment by riverswb** [comment]
@DavidKnott thanks, don't know why that wasn't showing up on my end or I missed it (more probable)

**Comment by ethanbennett** [comment]
Looks good! Sorry to keep you guys waiting.

**Pull request merged**
