### PR TITLE
Shipley issue 3

### PR DESCRIPTION
**Pull request by Sh1pley**
@ethanbennett @DavidKnott @riverswb 

please review, it does change the schema. adds a custom route handler to take category names and find them in the controller.. which may need to be moved elsewhere but works for this iteration.

### CODE REVIEW

**Review by riverswb — APPROVED** [review]
Looks good.

**Comment by ethanbennett** [comment]
@Sh1pley Nice!

**Comment by DavidKnott** [comment]
Well done!

**Comment by DavidKnott** [comment]
I resolved a simple conflict and now it looks good to go!

**Pull request merged**
