### PR TITLE
Brett: Issue 2 Pull Request

### PR DESCRIPTION
**Pull request by riverswb**
@Sh1pley , @DavidKnott , @ethanbennett 

Issue two is ready to merge to master.

### CODE REVIEW

**Comment by ethanbennett** [comment]
Nice, looks good to me!

**Comment by Sh1pley** [comment]
holy hound hating on your quotes. is there a way to turn that down? other than that I like it!

**Comment by riverswb** [comment]
@Sh1pley I've been reading up on how to tune that down, I think I've got some config files setup to keep the "Missing frozen string literal" down, next is the single quote comments...

**Comment by DavidKnott** [comment]
Looks like some great work! I'm merging it.

**Comment by riverswb** [comment]
Thanks guys

**Pull request merged**
