### PR TITLE
Initial styling

### PR DESCRIPTION
**Pull request by ethanbennett**
@riverswb @Sh1pley @DavidKnott Here's everything but a navbar on top and the footer, which I'll start with today unless we have other features to worry about soon.

### CODE REVIEW

**Comment by Sh1pley** [comment]
nice! I need style lessons from you.

**Review by riverswb — APPROVED** [review]
Looks good to me.  Nice work!

**Comment by DavidKnott** [comment]
Looks good, like they style.

**Comment by ethanbennett** [comment]
Thanks!

**Pull request merged**
