### PR TITLE
fix to database error

### PR DESCRIPTION
**Pull request by Sh1pley**
adding bretts branch as a problem solver

@DavidKnott @ethanbennett 
please confirm that this fixes our issues

### CODE REVIEW

**Comment by ethanbennett** [comment]
I think it technically counts as a miracle if the solution appeared without any of us figuring out the problem

**Review by ethanbennett — APPROVED** [review]

**Comment by riverswb** [comment]
@DavidKnott @Sh1pley @ethanbennett  

issue 12 is complete, all tests are passing.
When orders are created the have a status of "?" as a place holder, but I've got to take a break to eat and stuff so I'm going to make that a card on waffle

**Comment by Sh1pley** [comment]
Awesome! I like all of this.

**Review by ethanbennett — APPROVED** [review]

**Comment by DavidKnott** [comment]
Looks good  I'm gonna merge

**Pull request merged**
