### PR TITLE
add more tests and sad paths

### PR DESCRIPTION
**Pull request by Sh1pley**
@riverswb @DavidKnott @ethanbennett 
subject pretty much nails it.

### CODE REVIEW

**Review by riverswb — CHANGES_REQUESTED** [review]
Have you run the full test suite?

(From now on I will make these comments as request changes unless it is stated in the Pull Request)

**Comment by Sh1pley** [comment]
full test suite passing as of now!

**Review by riverswb — APPROVED** [review]

**Comment by ethanbennett** [comment]
Good call on the sad paths!

**Comment by DavidKnott** [comment]
I approve and will merge, nice work!

**Pull request merged**
